# Generated by Django 4.1.2 on 2022-10-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zipcodes_playlist_genre_followedevent_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='user',
        ),
        migrations.RemoveField(
            model_name='followedevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zipcodes',
            name='user',
        ),
    ]
