# Generated by Django 4.1.2 on 2022-10-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='artist_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
