# Generated by Django 4.1.2 on 2022-10-12 03:56

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_artists_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='followedevent',
            name='event_seatgeek_id',
            field=models.IntegerField(default=1, verbose_name=enum.unique),
            preserve_default=False,
        ),
    ]
